<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Partner.Import.Worker-0a642272-5080-443b-b2b1-c42390b81072</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Partner.Api\Partner.Api.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.14" />
  </ItemGroup>
</Project>
